### ISSUE TITLE
Enable drag up to close, too

### ISSUE THREAD

**Issue by JuanRdBO** [BooYeu/react-native-reanimated-viewer#1]
I really like this implementation! Would love to enable users to drag up to close too.

Disabling the condition `(Date.now().valueOf() - dragLastTime.value > 500 || event.translationY <= 0)` in the `imageDragGestureY` function would do the trick. Maybe a setting can be included in the props?

**Comment by BooYeu** [comment]
Thank you for your support, the props dragUpToCloseEnabled has been added in v1.0.1, you can see if it meets your needs, if there is any problem, you can reopen the issue
