### ISSUE TITLE
[iOS, Android] - Swipe up gesture to close image view not working

### ISSUE THREAD

**Issue by crank-chips** [BooYeu/react-native-reanimated-viewer#11]
At the moment, the image viewer can only be closed by swiping down. Swiping up does not have any effect.

https://github.com/BooYeu/react-native-reanimated-viewer/assets/17419029/fe8edff2-4d60-47b6-8e9c-63fbe4ab835d

**Comment by BooYeu** [comment]
Thanks for your feedback.
I will fix the props dragUpToCloseEnabled next week

**Comment by BooYeu** [comment]
You can try to use dragUpToCloseEnabled props
