### ISSUE TITLE
[Android] - System bars are not black on ImageViewer

### ISSUE THREAD

**Issue by crank-chips** [BooYeu/react-native-reanimated-viewer#13]
StatusBar backgroundColor="#000" on Android doesn's have effect on Android

<img width="336" alt="android_system_bars" src="https://github.com/BooYeu/react-native-reanimated-viewer/assets/17419029/e160208a-6c8c-4d46-9b12-cd4ebf27d693">

**Comment by BooYeu** [comment]
Thank you for your feeaback. This is my mistake. I will release a version next week

**Comment by BooYeu** [comment]
You can try v1.2.3. If this is still a problem, you can reopen this issue any time
