### ISSUE TITLE
[iOS, Android] - Pan on zoomed image doesn't have momentum

### ISSUE THREAD

**Issue by crank-chips** [BooYeu/react-native-reanimated-viewer#14]
When swiping on zoomed image I expect to see momentum of the gesture after the gesture ends. Currently, it ends up moving immediately after the gesture ends

https://github.com/BooYeu/react-native-reanimated-viewer/assets/17419029/5a3264bf-60cf-4609-9741-078dc817ac69

**Comment by BooYeu** [comment]
You can try v1.2.3. If this is still a problem, you can reopen this issue any time
