### ISSUE TITLE
Feature Request: Any plan to support multiple images in full screen?

### ISSUE THREAD

**Issue by kuldip-simform** [BooYeu/react-native-reanimated-viewer#15]
I would like to know if you are planning to support multiple images in full screen mode
 for eg. in readme we have list of 3 images and user can enlarge each image but is it possible to add feature that in enlarged screen user can swipe left or right to change images?

**Comment by BooYeu** [comment]
user can swipe left or right to change images in enlarged screen now

**Comment by BooYeu** [comment]
You can refer to the example in the gif. It has a demo of sliding in the enlarged screen

**Comment by kuldip-simform** [comment]
Thank you for your prompt resolution.
