### ISSUE TITLE
[iOS, Android] - Image "jumps" from right to the left when closed by dragging down

### ISSUE THREAD

**Issue by crank-chips** [BooYeu/react-native-reanimated-viewer#17]
After fixing this issue https://github.com/BooYeu/react-native-reanimated-viewer/issues/10 the new issue was discovered

When dragging the image down to close it moves to the right first and then "jumps" to the original position

To reproduce you can use code from issue https://github.com/BooYeu/react-native-reanimated-viewer/issues/10

https://github.com/BooYeu/react-native-reanimated-viewer/assets/17419029/15f08dd9-a9a0-4359-9251-1492d212df01

**Comment by BooYeu** [comment]
fixed in 1.3.0
