### ISSUE TITLE
[Feature request] Disable close on tap

### ISSUE THREAD

**Issue by gregamann** [BooYeu/react-native-reanimated-viewer#19]
Hi !
That's a nice project, your rock !
Is there a way to allow closing image-viewer only on swipe up or bot ?

I accidentally often close viewer "on simple tap" ^^
Thanks a lot

**Comment by BooYeu** [comment]
Thank you for your approval
You can try v1.3.0 & shouldCloseViewer={({gesture}) => gesture !== GestureEnum.TAP}
