### ISSUE TITLE
Crash on Android and iOS (less often)

### ISSUE THREAD

**Issue by JuanRdBO** [BooYeu/react-native-reanimated-viewer#2]
I have experienced a few crashes on Android and iOS. What has worked for me has been to put `runOnJs(true)` on the `imageDragGestureY ` function.

Also including wrapping all the .onStart(), .onUpdate() and .onEnd() in a try-catch helped.

Here is the stacktrace:
![image](https://user-images.githubusercontent.com/28183468/229872208-45db3170-0579-4f1c-89fc-84a864253191.png)

**Comment by BooYeu** [comment]
Thank you for your feedback, it seems that you are using v0.2.3, can you use v1.0.1 to see if there will be a crash problem ?

**Comment by BooYeu** [comment]
At present, there should be no flashback problem in the new version. I will temporarily close this issue.
If you find there is still a problem, you can open it again at any time.
