### ISSUE TITLE
[Issue][Android] - can't loaded image from camera 

### ISSUE THREAD

**Issue by WangShayne** [BooYeu/react-native-reanimated-viewer#26]
Opening a photo from the camera always shows the loading icon, but online images work just fine;

image info
![image](https://github.com/BooYeu/react-native-reanimated-viewer/assets/17644818/b716e1ff-b921-4e49-be6d-20d0e911202a)

https://github.com/BooYeu/react-native-reanimated-viewer/assets/17644818/2982813c-8c4f-487d-a147-0698d0888391

**Comment by WangShayne** [comment]
If the utility static array can be loaded correctly, but the utility useState updates the array, the pictures added later cannot be displayed and keep loading.

**Comment by BooYeu** [comment]
Could you show me your codes ?

**Comment by WangShayne** [comment]
sorry i remove the codes.
ex: 
```
const [images,setImages]=useState([])

const takePhoto = () => {
    //get a image file uri
    setImages(images => [...images, {uri: image.uri}])
}

```

**Comment by BooYeu** [comment]
Could you try this:
```
const [images,setImages]=useState([])

const takePhoto = () => {
    //get a image file uri
    setImages(images => [...images, image])
}

```

**Comment by WangShayne** [comment]
> Could you try this:
> 
> ```
> const [images,setImages]=useState([])
> 
> const takePhoto = () => {
>     //get a image file uri
>     setImages(images => [...images, image])
> }
> ```

same result
