### ISSUE TITLE
Disable or enable image scaling when dragging up

### ISSUE THREAD

**Issue by JuanRdBO** [BooYeu/react-native-reanimated-viewer#3]
Currently, when dragging up, the image scale changes, but it would be so much more flexible to programmatically enable or disable this with props. Currently what causes this, is in the line 

```
const changeHeight =
          (((currentOriginalImageSize?.height || 0) - screenDimensions.height) *
            (imageScaleValue === 1 ? imageYValue : 1)) /
          screenDimensions.height;
```

with the value of imageYValue.

**Comment by BooYeu** [comment]
Thank you for your support, the props dragUpToCloseEnabled has been added in v1.0.1, you can see if it meets your needs, if there is any problem, you can reopen the issue
