### ISSUE TITLE
Error build

### ISSUE THREAD

**Issue by fukemy** [BooYeu/react-native-reanimated-viewer#8]
Hi, I got this error when build, can u help?
`[Error: InternalError Metro has encountered an error: While trying to resolve module `react-hooks-extension` from file `/.../node_modules/react-native-reanimated-viewer/src/components/imageViewer.tsx`, the package `/Users/vedaxm1/Documents/Work/VedaxLink/node_modules/react-hooks-extension/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/./node_modules/react-hooks-ext..ension/dist/index.cjs`. Indeed, none of these files exist:

  * /...node_modules/react-hooks-extension/dist/index.cjs(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)

**Comment by BooYeu** [comment]
v1.2.0 fixed this problem
